# Generated by Django 6.0.1 on 2026-01-10 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='budget',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='consulted_others',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='sketches/'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='other_designers',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='project_type',
            field=models.CharField(choices=[('RESIDENTIAL', 'Residential'), ('COMMERCIAL', 'Commercial'), ('HOSPITALITY', 'Hospitality'), ('OTHER', 'Other')], default='RESIDENTIAL', max_length=20),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='timeline',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
